### ISSUE TITLE
Alchemy Creating Wrong Account Record Type

### ISSUE THREAD

**Issue by BhargavRentala** [palmetto-tech/Palmetto#311]
Alchemy is creating Business Development Record type account in salesforce instead of 3rd- Party Design Sales record type.

Field Name: RecordType
Business Development:  0121a0000002MZB
                                       0121a0000002MZBAA2(18 Charid)
3rd - Party Design Sales:0121a000000eQb9 
                                       0121a000000eQb9AAE(18 charID)

**Comment by kellengarnaas** [comment]
Upon a deep dive into this issue, I've resorted to running salesforce api requests manually. I've discovered that upon a request to update the RecordTypeId for an Account, I'm receiving the following error:

`{\"errors\":[{\"message\":\"The formula in the \\\"Set Reseller Type\\\" rule or process is invalid due to the following:<br/>Field $Setup.ia_crm__Reseller_Types__c.ia_crm__Types__c does not exist. Check spelling.\",\"statusCode\":\"CANNOT_INSERT_UPDATE_ACTIVATE_ENTITY\"}`

This seems very strange to me as nothing having to do with reseller type is being referenced at all by the API call I am making. I'm wondering if this is something triggered on the Salesforce side.
